{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cc11749a",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 81, in search\n",
      "    x=n.searchdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 81, in search\n",
      "    x=n.searchdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 53, in delete\n",
      "    a=l.index(s)\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 3191, in index\n",
      "    i = self.tk.call(self._w, 'index', index)\n",
      "_tkinter.TclError: bad listbox index \"\": must be active, anchor, end, @x,y, or a number\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 53, in delete\n",
      "    a=l.index(s)\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 3191, in index\n",
      "    i = self.tk.call(self._w, 'index', index)\n",
      "_tkinter.TclError: bad listbox index \"\": must be active, anchor, end, @x,y, or a number\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 53, in delete\n",
      "    a=l.index(s)\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 3191, in index\n",
      "    i = self.tk.call(self._w, 'index', index)\n",
      "_tkinter.TclError: bad listbox index \"\": must be active, anchor, end, @x,y, or a number\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 67, in update\n",
      "    n.updatedb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 67, in update\n",
      "    n.updatedb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 46, in insert\n",
      "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n",
      "('ee', 'eee', 'eee', 'eee')\n",
      "ee\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 60, in delete\n",
      "    n.deletedb(c)\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 67, in update\n",
      "    n.updatedb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 46, in insert\n",
      "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 46, in insert\n",
      "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 46, in insert\n",
      "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 46, in insert\n",
      "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 46, in insert\n",
      "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 46, in insert\n",
      "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 46, in insert\n",
      "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 46, in insert\n",
      "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 53, in delete\n",
      "    a=l.index(s)\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 3191, in index\n",
      "    i = self.tk.call(self._w, 'index', index)\n",
      "_tkinter.TclError: bad listbox index \"\": must be active, anchor, end, @x,y, or a number\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 53, in delete\n",
      "    a=l.index(s)\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 3191, in index\n",
      "    i = self.tk.call(self._w, 'index', index)\n",
      "_tkinter.TclError: bad listbox index \"\": must be active, anchor, end, @x,y, or a number\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 53, in delete\n",
      "    a=l.index(s)\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 3191, in index\n",
      "    i = self.tk.call(self._w, 'index', index)\n",
      "_tkinter.TclError: bad listbox index \"\": must be active, anchor, end, @x,y, or a number\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 53, in delete\n",
      "    a=l.index(s)\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 3191, in index\n",
      "    i = self.tk.call(self._w, 'index', index)\n",
      "_tkinter.TclError: bad listbox index \"\": must be active, anchor, end, @x,y, or a number\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 53, in delete\n",
      "    a=l.index(s)\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 3191, in index\n",
      "    i = self.tk.call(self._w, 'index', index)\n",
      "_tkinter.TclError: bad listbox index \"\": must be active, anchor, end, @x,y, or a number\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "6\n",
      "('ee', 'eee4', 'eee', 'eee')\n",
      "ee\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 60, in delete\n",
      "    n.deletedb(c)\n",
      "NameError: name 'n' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "5\n",
      "('ee', 'eee4', 'eee', 'eee')\n",
      "ee\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 60, in delete\n",
      "    n.deletedb(c)\n",
      "NameError: name 'n' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n",
      "('ee', 'eee4', 'eee', 'eee')\n",
      "ee\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 60, in delete\n",
      "    n.deletedb(c)\n",
      "NameError: name 'n' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2\n",
      "('ee', 'eee4', 'eee', 'eee')\n",
      "ee\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 60, in delete\n",
      "    n.deletedb(c)\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 67, in update\n",
      "    n.updatedb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2\n",
      "('ee', 'eee4', 'eee', 'eee')\n",
      "ee\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 60, in delete\n",
      "    n.deletedb(c)\n",
      "NameError: name 'n' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n",
      "('ee', 'eee4', 'eee', 'eee')\n",
      "ee\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 60, in delete\n",
      "    n.deletedb(c)\n",
      "NameError: name 'n' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n",
      "('ee', 'eee4', 'eee', 'eee')\n",
      "ee\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 60, in delete\n",
      "    n.deletedb(c)\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 77, in view\n",
      "    x=n.viewdb()\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 46, in insert\n",
      "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 67, in update\n",
      "    n.updatedb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 67, in update\n",
      "    n.updatedb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 67, in update\n",
      "    n.updatedb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 46, in insert\n",
      "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
      "NameError: name 'n' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n",
      "('ee', 'eee4', 'eee', 'eee')\n",
      "ee\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\MAC\\anaconda3\\lib\\tkinter\\__init__.py\", line 1892, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"C:\\Users\\MAC\\AppData\\Local\\Temp\\ipykernel_11876\\1629037726.py\", line 60, in delete\n",
      "    n.deletedb(c)\n",
      "NameError: name 'n' is not defined\n"
     ]
    }
   ],
   "source": [
    "import sqlite3 as sq\n",
    "conn=sq.connect(\"DB.db\")\n",
    "cursor=conn.cursor()\n",
    "cursor.execute(\"\"\"CREATE TABLE if not exists DB(id INTEGER PRIMARY KEY autoincrement,title text,author text,year INTEGER,isbn INTEGER);\"\"\")\n",
    "def insertdb(b,c,d,e):    \n",
    "    conn=sq.connect(\"DB.db\")\n",
    "    cursor=conn.cursor()\n",
    "    DB=(b,c,d,e)\n",
    "    cursor.execute(\"INSERT INTO DB VALUES(NULL,?,?,?,?);\",DB)\n",
    "    print('insert successful')\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "def updatedb(a,b,c,d):\n",
    "    conn=sq.connect(\"DB.db\")\n",
    "    cursor=conn.cursor()\n",
    "    cursor.execute(\"UPDATE DB SET title=?,author=?,year=?,isbn=?\",(a,b,c,d))\n",
    "    print('update successful')\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "def deletedb(a):\n",
    "    conn=sq.connect(\"DB.db\")\n",
    "    cursor=conn.cursor()\n",
    "    cursor.execute(\"DELETE FROM DB WHERE id=?\",(a,))\n",
    "    print('delete successful')\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "def searchdb(b=None,c=None,d=None,e=None):\n",
    "    conn=sq.connect(\"DB.db\")\n",
    "    cursor=conn.cursor()\n",
    "    cursor.execute(\"SELECT * FROM DB WHERE title=? or author=? or year=? or isbn=?\",(b,c,d,e))\n",
    "    return cursor.fetchone()\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "def viewdb():\n",
    "    conn=sq.connect(\"DB.db\")\n",
    "    cursor=conn.cursor()\n",
    "    cursor.execute(\"SELECT * FROM DB\")\n",
    "    return(cursor.fetchall())\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "    \n",
    "    \n",
    "def insert():\n",
    "    w=[e1.get(),e2.get(),e3.get(),e4.get()]\n",
    "    l.insert(END,w)\n",
    "    n.insertdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
    "    e1.delete(0,END)\n",
    "    e2.delete(0,END)\n",
    "    e3.delete(0,END)\n",
    "    e4.delete(0,END)\n",
    "def delete():\n",
    "    s=l.curselection()\n",
    "    a=l.index(s)\n",
    "    b=l.get(a)\n",
    "    c=b[0]\n",
    "    l.delete(s)\n",
    "    print(a)\n",
    "    print(b)\n",
    "    print(c)\n",
    "    n.deletedb(c)\n",
    "    e1.delete(0,END)\n",
    "    e2.delete(0,END)\n",
    "    e3.delete(0,END)\n",
    "    e4.delete(0,END)\n",
    "def update():\n",
    "    s=l.curselection()\n",
    "    n.updatedb(e1.get(),e2.get(),e3.get(),e4.get())\n",
    "    l.delete(s)\n",
    "    w=[e1.get(),e2.get(),e3.get(),e4.get()]\n",
    "    l.insert(s,w)\n",
    "    e1.delete(0,END)\n",
    "    e2.delete(0,END)\n",
    "    e3.delete(0,END)\n",
    "    e4.delete(0,END)\n",
    "def view():\n",
    "    l.delete(0,END)\n",
    "    x=n.viewdb()\n",
    "    for item in x:\n",
    "        l.insert(END,item)\n",
    "def search():\n",
    "    x=n.searchdb(e1.get(),e2.get(),e3.get(),e4.get())\n",
    "    e1.delete(0,END)\n",
    "    e2.delete(0,END)\n",
    "    e3.delete(0,END)\n",
    "    e4.delete(0,END) \n",
    "    e1.insert(END,x[1])\n",
    "    e2.insert(END,x[2])\n",
    "    e3.insert(END,x[3])\n",
    "    e4.insert(END,x[4]) \n",
    "    \n",
    "from tkinter import *\n",
    "windows=Tk()\n",
    "Frame1 = Frame(windows)\n",
    "Frame1.pack( side = TOP )\n",
    "l1=Label(Frame1,text=' Title')\n",
    "l1.pack(side=LEFT)\n",
    "e1=Entry(Frame1)\n",
    "e1.pack(side=LEFT)\n",
    "l2=Label(Frame1,text='Author')\n",
    "l2.pack(side=LEFT)\n",
    "e2=Entry(Frame1)\n",
    "e2.pack(side=LEFT)\n",
    "\n",
    "Frame2 = Frame(windows)\n",
    "Frame2.pack( side = TOP )\n",
    "l3=Label(Frame2,text='Year')\n",
    "l3.pack(side=LEFT)\n",
    "e3=Entry(Frame2)\n",
    "e3.pack(side=LEFT)\n",
    "l4=Label(Frame2,text='ISBN    ')\n",
    "l4.pack(side=LEFT)\n",
    "e4=Entry(Frame2)\n",
    "e4.pack(side=LEFT)\n",
    "\n",
    "l= Listbox(windows,width=30)\n",
    "l.pack( side = LEFT, fill = BOTH )\n",
    "    \n",
    "Frame3 = Frame(windows)\n",
    "Frame3.pack( side = RIGHT )\n",
    "b1=Button(Frame3,text='View All',command=view,width=15)\n",
    "b1.pack(side=TOP)\n",
    "b2=Button(Frame3,text='Search Entry',command=search,width=15)\n",
    "b2.pack(side=TOP)\n",
    "b3=Button(Frame3,text='Add Entry',command=insert,width=15)\n",
    "b3.pack(side=TOP)\n",
    "b4=Button(Frame3,text='Update Selected',command=update,width=15)\n",
    "b4.pack(side=TOP)\n",
    "b5=Button(Frame3,text='Delete Selected',command=delete,width=15)\n",
    "b5.pack(side=TOP)\n",
    "\n",
    "\n",
    "windows.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8901463c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "58c4f494",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
